# Generated by Django 5.1 on 2024-09-17 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='location',
        ),
        migrations.AddField(
            model_name='session',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='SessionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medsessions.location')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='medsessions.session')),
            ],
            options={
                'unique_together': {('session', 'date', 'start_time', 'location')},
            },
        ),
    ]
