FROM python:3.12-slim

WORKDIR /app

COPY ../deploy/backend-requirements.txt /app/
RUN pip install --no-cache-dir -r backend-requirements.txt

COPY ../backend/medschool /app/

EXPOSE 8000

RUN python manage.py migrate

CMD ["gunicorn", "medschool.wsgi:application", "--bind", "0.0.0.0:8000"]
